# Not correct for Perlmutter
#FROM ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01
#FROM registry.nersc.gov/library/nersc/mpich:4.0.2-haswell
ARG REGISTRY=registry.nersc.gov
ARG IMAGE=library/nersc/mpich
ARG TAG=4.0.2-haswell
ARG BUILD_DATE
FROM ${REGISTRY}/${IMAGE}:${TAG}
#########################################
# Base Container Env:

RUN apt-get update -y && \
    apt-get -y upgrade && \
    apt-get -y install \
    clangd \
    git \
    git-doc \
    git-man \
    zlib1g-dev \
    gcc-10 \
    gfortran-10 \
    libjpeg-dev \
    unzip \
    wget2 \
    cmake \
    mpich \
    m4 \
    autoconf \
    automake \
    libtool \
    vim \
    patch \
    xz-utils \
    bzip2 \
    cpp-10 \
    libblas3 \
    liblapack-dev \
    libgmp-dev \
    libmpc-dev \
    flex \
    nano \
    libfmt-dev \
    openssl \
    libx11-dev \
    libffi-dev

RUN apt clean -y

# End base env
######################


## Perlmutter-specific additions
ENV NERSC_HOST=perlmutter
WORKDIR /exawind-entry
RUN git clone --recursive https://github.com/sandialabs/spack-manager
ENV SPACK_MANAGER=spack-manager
COPY drive.sh /exawind-entry 

RUN ["/bin/bash", "drive.sh"]
RUN echo export SPACK_MANAGER=spack-manager >> /etc/bash.bashrc \
&& echo export NERSC_HOST=perlmutter >> /etc/bash.bashrc \
&& echo "source $SPACK_MANAGER/start.sh" >> /etc/bash.bashrc \
&& echo spack-start >> /etc/bash.bashrc \
&& echo create-exawind-snapshot.sh >> /etc/bash.bashrc \
&& echo spack install >> /etc/bash.bashrc \
&& echo spack clean -a >> /etc/bash.bashrc 


# NOTES:
#source $SPACK_MANAGER/start.sh
#spack-start
#export SPACK_MANAGER_MACHINE=perlmutter
#create-exawind-snapshot.sh
#spack install
#spack clean -a
#rm -rf[?4m/root


LABEL ${NERSC_HOST}.build-date=${BUILD_DATE}
