compilers:
  - compiler:
      spec: gcc@9.3.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/9.3.0
      - libfabric/1.11.0.4.75
      - craype-network-ofi
      - craype-accel-amd-gfx908
      environment: {}
      extra_rpaths: []
