packages:
  cray-mpich:
    version: [8.1.12]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.12%gcc@9.3.0"
        modules:
          - cray-mpich/8.1.12
          - gcc/9.3.0
          - libfabric/1.11.0.4.75
          - craype-network-ofi
  hip:
    version: [4.5.0]
    buildable: false
    externals:
      - spec: hip@4.5.0
        prefix: /opt/rocm-4.5.0/hip
        modules:
          - craype-accel-amd-gfx908
  hsa-rocr-dev:
    version: [4.5.0]
    buildable: false
    externals:
      - spec: hsa-rocr-dev@4.5.0
        prefix: /opt/rocm-4.5.0/hsa
        modules:
          - craype-accel-amd-gfx908
  llvm-amdgpu:
    version: [4.5.0]
    buildable: false
    externals:
      - spec: llvm-amdgpu@4.5.0
        prefix: /opt/rocm-4.5.0/llvm
  all:
    compiler:
      - gcc@9.3.0
    providers:
      mpi: [cray-mpich@8.1.12]
      blas: [openblas]
      lapack: [openblas]
