packages:
  cray-mpich:
    version: [8.1.12]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.12%gcc@9.3.0"
        modules:
          - cray-mpich/8.1.12
          - gcc/9.3.0
          - libfabric/1.11.0.4.75
          - craype-network-ofi
      - spec: "cray-mpich@8.1.12%clang@13.0.0"
        modules:
          - cray-mpich/8.1.12
          - rocm/5.0.0
          - libfabric/1.11.0.4.75
          - craype-network-ofi
      - spec: "cray-mpich@8.1.12%cce@13.0.0"
        modules:
          - cray-mpich/8.1.12
          - cce/13.0.0
          - libfabric/1.11.0.4.75
          - craype-network-ofi
  hip:
    version: [5.0.0]
    buildable: false
    externals:
      - spec: hip@5.0.0
        prefix: /opt/rocm-5.0.0/hip
        modules:
          - craype-accel-amd-gfx908
  hsa-rocr-dev:
    version: [5.0.0]
    buildable: false
    externals:
      - spec: hsa-rocr-dev@5.0.0
        prefix: /opt/rocm-5.0.0/hsa
        modules:
          - craype-accel-amd-gfx908
  llvm-amdgpu:
    version: [5.0.0]
    buildable: false
    externals:
      - spec: llvm-amdgpu@5.0.0
        prefix: /opt/rocm-5.0.0/llvm
        modules:
          - craype-accel-amd-gfx908
  boost:
    version: [1.73.0]
    buildable: false
    externals:
      - spec: boost@1.73.0
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/boost-1.73.0-nnaww46oatokeudktwfaxu6dvl7zsyhw
        modules:
          - boost/1.73.0
#  hdf5:
#    version: [1.12.0.7]
#    buildable: false
#    externals:
#      - spec: hdf5@1.12.0.7
#        prefix: /opt/cray/pe/hdf5-parallel/1.12.0.7/crayclang/10.0
#        modules:
#          - cray-hdf5-parallel/1.12.0.7
#  parallel-netcdf:
#    version: [1.12.1.7]
#    buildable: false
#    externals:
#      - spec: parallel-netcdf@1.12.1.7
#        prefix: /opt/cray/pe/parallel-netcdf/1.12.1.7/amd/4.3
#        modules:
#          - cray-parallel-netcdf/1.12.1.7
  cmake:
    version: [3.22.1]
    buildable: false
    externals:
      - spec: cmake@3.22.1
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.22.1-wd2ptgormfxhkw3fiac75fiznbzcvpah
        modules:
          - cmake/3.22.1
  zlib:
    version: [1.2.11]
    buildable: false
    externals:
      - spec: zlib@1.2.11
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/zlib-1.2.11-zuyclcfig4tizmb2bm2h4roqsp3rwn2y
        modules:
          - zlib/1.2.11
  perl:
    require: "@5.34.0"
    buildable: false
    externals:
      - spec: perl@5.34.0
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/perl-5.34.0-2f4kqqwg4xkrrapb5peh5m6fw2cargdl
        modules:
          - perl/5.34.0
  openblas:
    version: [0.3.17]
    buildable: false
    externals:
      - spec: openblas@0.3.17
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/openblas-0.3.17-54x7v5e4i6yxqs6j5nebrbztpy4lftj4
        modules:
          - openblas/0.3.17
  xz:
    version: [5.2.5]
    buildable: false
    externals:
      - spec: xz@5.2.5
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/xz-5.2.5-tm5p6wqkxf6qk6cizuqhtql5sup4ftzo
        modules:
          - xz/5.2.5
  libxml2:
    version: [2.9.10]
    buildable: false
    externals:
      - spec: libxml2@2.9.10
        prefix: /sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/libxml2-2.9.10-wmgh7x4srsgkudl3bna24fekjnncgvcw
        modules:
          - libxml2/2.9.10
  all:
    compiler:
      #- gcc@9.3.0
      - clang@13.0.0
    providers:
      mpi: [cray-mpich@8.1.12]
      blas: [openblas]
      lapack: [openblas]
    variants: amdgpu_target=gfx908
