packages:
  cray-mpich:
    version: [8.1.10]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.10%gcc@9.3.0"
        modules:
          - cray-mpich/8.1.10
          - gcc/9.3.0
          - libfabric/1.11.0.4.75
  hip:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: "hip@4.3.0"
        modules:
          - rocm/4.3.0
          - craype-accel-amd-gfx908
  hsa-rocr-dev:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: "hsa-rocr-dev@4.3.0"
        modules:
          - rocm/4.3.0
          - craype-accel-amd-gfx908
  llvm-amdgpu:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: "llvm-amdgpu@4.3.0"
        modules:
          - rocm/4.3.0
          - craype-accel-amd-gfx908
  all:
    compiler:
      - gcc@9.3.0
    providers:
      mpi:
        - cray-mpich@8.1.10
      blas: [openblas]
      lapack: [openblas]
