packages:
  cray-mpich:
    version: [8.1.10]
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.10%gcc@9.3.0"
        modules:
          - cray-mpich/8.1.10
          - gcc/9.3.0
          - libfabric/1.11.0.4.75
  hip:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: hip@4.3.0
        prefix: /opt/rocm-4.3.0/hip
  hsa-rocr-dev:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: hsa-rocr-dev@4.3.0
        prefix: /opt/rocm-4.3.0/hsa
  llvm-amdgpu:
    version: [4.3.0]
    buildable: false
    externals:
      - spec: llvm-amdgpu@4.3.0
        prefix: /opt/rocm-4.3.0/llvm
  all:
    compiler:
      - gcc@9.3.0
    providers:
      mpi: [cray-mpich@8.1.10]
      blas: [openblas]
      lapack: [openblas]
