modules:
  default:
    tcl:
      all:
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
      mpt:
        environment:
          set:
            'MPI_TYPE_DEPTH': '16'
            'MPI_XPMEM_ENABLED': 'disabled'
            'MPI_IB_CONGESTED': 'true'
            'MPI_IGNORE_PBS': 'true'
