compilers:
- compiler:
    paths:
      cc: /sw/summit/gcc/10.2.0/bin/gcc
      cxx: /sw/summit/gcc/10.2.0/bin/g++
      f77: /sw/summit/gcc/10.2.0/bin/gfortran
      fc: /sw/summit/gcc/10.2.0/bin/gfortran
    operating_system: rhel8
    target: ppc64le
    modules:
      - gcc/10.2.0
    environment: {}
    extra_rpaths:
      - /sw/summit/gcc/10.2.0/lib
      - /sw/summit/gcc/10.2.0/lib64
      - /sw/summit/gcc/10.2.0/libexec
    flags: {}
    spec: gcc@10.2.0
#- compiler:
#    paths:
#      cc: /sw/summit/gcc/9.3.0-1/bin/gcc
#      cxx: /sw/summit/gcc/9.3.0-1/bin/g++
#      f77: /sw/summit/gcc/9.3.0-1/bin/gfortran
#      fc: /sw/summit/gcc/9.3.0-1/bin/gfortran
#    operating_system: rhel8
#    target: ppc64le
#    modules:
#      - gcc/9.3.0
#    environment: {}
#    extra_rpaths:
#      - /sw/summit/gcc/9.3.0-1/lib
#      - /sw/summit/gcc/9.3.0-1/lib64
#      - /sw/summit/gcc/9.3.0-1/libexec
#    flags: {}
#    spec: gcc@9.3.0
