packages:
  all:
    target: [ppc64le]
    compiler:
      - gcc@10.2.0
    providers:
      mpi:
        - spectrum-mpi@10.4
    variants: cuda_arch=70 
  spectrum-mpi:
    version: [10.4]
    buildable: false
    externals:
      - spec: "spectrum-mpi@10.4%gcc@10.2.0"
        modules:
          - gcc/10.2.0
          - spectrum-mpi/10.4.0.3-20210112
  cuda:
    version: [11.4.2]
    buildable: false
    externals:
      - spec: "cuda@11.4.2%gcc"
        modules:
          - cuda/11.4.2
      #- spec: "cuda@11.3.1%gcc"
      #  modules:
      #    - cuda/11.3.1
      #- spec: "cuda@11.0.3%gcc"
      #  modules:
      #    - cuda/11.0.3
  netcdf-c:
    require: "@4.8.1"
    buildable: false
    externals:
      - spec: "netcdf-c@4.8.1%gcc"
        modules:
          - netcdf-c/4.8.1
  parallel-netcdf:
    version: [1.12.2]
    buildable: false
    externals:
      - spec: "parallel-netcdf@1.12.2%gcc"
        modules:
          - parallel-netcdf/1.12.2
  cmake:
    version: [3.23.2]
    buildable: false
    externals:
      - spec: "cmake@3.23.2%gcc"
        modules:
          - cmake/3.23.2
  zlib:
    version: [1.2.11]
    buildable: false
    externals:
      - spec: "zlib@1.2.11%gcc"
        modules:
          - zlib/1.2.11
  bzip2:
    version: [1.0.6]
    buildable: false
    externals:
      - spec: "bzip2@1.0.6%gcc"
        prefix: /usr/
  libxml2:
    version: [2.9.10]
    buildable: false
    externals:
      - spec: "libxml2@2.9.10%gcc"
        modules:
          - libxml2/2.9.10
  m4:
    version: [1.4.18]
    buildable: false
    externals:
      - spec: "m4@1.4.18%gcc"
        prefix: /usr/
  perl:
    version: [5.26.2]
    buildable: false
    externals:
      - spec: "perl@5.26.2%gcc"
        modules:
          - perl/5.26.2
  libtool:
    version: [2.4.2]
    buildable: false
    externals:
      - spec: "libtool@2.4.2%gcc"
        modules:
          - libtool/2.4.2
  autoconf:
    version: [2.69]
    buildable: false
    externals:
      - spec: "autoconf@2.69%gcc"
        modules:
          - autoconf/2.69
  automake:
    version: [1.16.1]
    buildable: false
    externals:
      - spec: "automake@1.16.1%gcc"
        modules:
          - automake/1.16.1
  pkgconf:
    version: [1.4.2]
    buildable: false
    externals:
      - spec: "pkgconf@1.4.2%gcc"
        prefix: /usr/
  python:
    require: "@3.7.7"
    buildable: false
    externals:
      - spec: "python@3.7.7%gcc"
        modules:
          - python/3.7.7
  netlib-lapack:
    version: [3.9.1]
    buildable: false
    externals:
      - spec: "netlib-lapack@3.9.1%gcc"
        modules:
          - netlib-lapack/3.9.1
  ncurses:
    version: [6.2]
    buildable: false
    externals:
      - spec: "ncurses@6.2%gcc"
        prefix: /usr/
  openssl:
    version: [1.1.1l]
    buildable: false
    externals:
      - spec: "openssl@1.1.1l%gcc"
        prefix: /usr/
  boost:
    version: [1.76.0]
    buildable: false
    externals:
      - spec: "boost@1.76.0%gcc"
        modules:
          - boost/1.76.0
  umpire:
    version: [6.0.0]
    buildable: false
    externals:
      - spec: "umpire@6.0.0-no_omp-shared%gcc"
        prefix: "/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/umpire-6.0.0-5qtgtts7nz2zunae7w7eeqgiqclb6uuv"
        modules:
          - umpire/6.0.0-no_omp-shared
