packages:
  spectrum-mpi:
    version: [10.4]
    buildable: false
    externals:
      - spec: "spectrum-mpi@10.4%gcc@10.2.0"
        modules:
          - gcc/10.2.0
          - spectrum-mpi/10.4.0.3-20210112
      #- spec: "spectrum-mpi@10.4%gcc@9.3.0"
      #  modules:
      #    - gcc/9.3.0
      #    - spectrum-mpi/10.4.0.3-20210112
      #- spec: "spectrum-mpi@10.4%gcc@7.5.0"
      #  modules:
      #    - gcc/7.5.0
      #    - spectrum-mpi/10.4.0.3-20210112
  cuda:
    version: [11.3.1]
    buildable: false
    externals:
      #- spec: "cuda@11.4.0%gcc@10.2.0"
      #  modules:
      #    - cuda/11.4.0
      - spec: "cuda@11.3.1%gcc@10.2.0"
        modules:
          - cuda/11.3.1
      #- spec: "cuda@11.0.3%gcc@10.2.0"
      #  modules:
      #    - cuda/11.0.3
      #- spec: "cuda@10.2.89%gcc@10.2.0"
      #  modules:
      #    - cuda/10.2.89
  all:
    compiler:
      - gcc@10.2.0
    providers:
      mpi:
        - spectrum-mpi@10.4
