spack:
  include:
  - packages.yaml
  - compilers.yaml
  - config.yaml
  - $SPACK_MANAGER/configs/base/packages.yaml
  definitions:
  - compilers: ['%gcc', '%clang']
  - core:
    - exawind+openfast+hypre ^openmpi@4.0.2
    - exawind~openfast~hypre ^openmpi@4.0.2
  specs:
  - matrix:
    - [$core]
    - [$compilers]
  - exawind%gcc+cuda+hypre+openfast ^cuda@11.2
  - exawind%gcc ^mvapich2
  view:
    default:
      root: .spack-env/view
      projections:
        all: '{compiler.name}/{compiler.version}/{name}/{version}/{hash:8}'
      link_type: symlink
  concretizer:
    unify: false
  packages:
    all:
      target: [x86_64]
      variants: [build_type=Release]
    boost:
      version: [1.80.0]
    openmpi:
      variants: [+legacylaunchers fabrics=auto schedulers=auto]
    python:
      variants: [~crypt]
