spack:
  include:
  - packages.yaml
  - compilers.yaml
  - config.yaml
  specs:
  - gcc@10.3.0
  - llvm@13+clang targets=x86 ~gold ^ninja@kitware
  # try a view to detect compilers
  view:
      root: .spack-env/view
      projections:
        all: '{compiler.name}/{compiler.version}/{name}/{version}/{hash:8}'
      link_type: symlink
  concretizer:
    unify: false
  packages:
    all:
      target: [x86_64]
      variants: [build_type=Release]
    gcc:
      variants: [build_type=Release +profiled +strip]
    mpc:
      variants: [libs=static]
    gmp:
      variants: [libs=static]
    mpfr:
      variants: [libs=static]
    zstd:
      variants: [libs=static]
    zlib:
      variants: [~shared]
