compilers:
  - compiler:
      spec: oneapi@2023.0.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: rhel8
      target: any
      modules:
      - PrgEnv-intel/8.3.3
      - intel/2023.0.0
      - craype/2.7.19
      - craype-x86-spr
      - cray-dsmml/0.2.2
      - cray-libsci/22.11.1.2
      - libfabric
      extra_rpaths: []
      environment: {}
