compilers:
  - compiler:
      spec: oneapi@2023.0.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: rhel8
      target: any
      modules:
      - PrgEnv-intel/8.3.3
      - intel/2023.0.0
      - craype/2.7.17
      - craype-x86-spr
      - cray-dsmml/0.2.2
      - cray-libsci/22.11.1.2
      - gcc/12.1.0
      - libfabric/1.15.2.0
      - craype-network-ofi
      - cray-pmi
      extra_rpaths:
        - /nopt/intel/oneapi/compiler/2023.0.0/linux/lib
        - /nopt/intel/oneapi/compiler/2023.0.0/linux/lib/x64
        - /nopt/intel/oneapi/compiler/2023.0.0/linux/lib/oclfpga/host/linux64/lib
        - /nopt/intel/oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin
        - /opt/cray/pe/gcc/12.2.0/snos/lib64
      environment: {}
