packages:
  cray-mpich:
    require: "@=8.1.21"
    buildable: false
    externals:
      - spec: "cray-mpich@=8.1.21%oneapi@2023.0.0"
        prefix: /opt/cray/pe/mpich/8.1.21/ofi/intel/19.0
        modules:
          - cray-mpich/8.1.21
          - craype-network-ofi
          - libfabric/1.15.2.0
  trilinos:
    require:
      - any_of: ["@13.4.0.2023.02.28", "@develop"]
  nalu-wind:
    variants: ~trilinos-solvers
  all:
    compiler:
      - oneapi@2023.0.0
    providers:
      mpi: [cray-mpich@8.1.21]
      blas: [openblas]
      lapack: [openblas]
    variants: build_type=Release cuda_arch=80
