compilers:
- compiler:
      spec: gcc@10.3.0
      paths:
        cc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gcc
        cxx: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/g++
        f77: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gfortran
        fc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gfortran
      flags: {}
      operating_system: rhel7
      target: x86_64
      modules: []
      environment:
        set:
          http_proxy: http://proxy.sandia.gov:80/
          https_proxy: http://proxy.sandia.gov:80/
      extra_rpaths: []
- compiler:
    spec: intel@2021.1.2
    paths:
      cc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/icc
      cxx: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/icpc
      f77: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/ifort
      fc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/ifort
    flags:
      cflags: -gcc-name=/projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gcc
      cxxflags: -gxx-name=/projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/g++
      fflags: -gcc-name=/projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gcc
    operating_system: rhel7
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/lib:/projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/lib64
        LIBRARY_PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/lib:/projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/lib64
        PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin
        C_INCLUDE_PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/include
        CPLUS_INCLUDE_PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/include
        INCLUDE: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/include
        CMAKE_PREFIX_PATH: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/
      set:
        I_MPI_CC: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/icc
        I_MPI_CXX: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/icpc
        I_MPI_FC: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2021.1.2-lufoj3442adjwmyj2djuozq5aec3ofn2/compiler/2021.1.2/linux/bin/intel64/ifort
    extra_rpaths: []
- compiler:
    spec: clang@12.0.1
    paths:
      cc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/llvm-12.0.1-4ld5bciw4oetcntm2hgn23pklymf55ou/bin/clang
      cxx: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/llvm-12.0.1-4ld5bciw4oetcntm2hgn23pklymf55ou/bin/clang++
      f77: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gfortran
      fc: /projects/cde/v3/tlcc2/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-bxx4ufppf7l3xlbvdinnusa4e6ykqok5/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    environment: {}
    extra_rpaths:
    - /opt/rh/devtoolset-8/root/usr/lib64
    modules: []
    flags: {}
    operating_system: rhel7
    paths:
      cc: /opt/rh/devtoolset-8/root/usr/bin/gcc
      cxx: /opt/rh/devtoolset-8/root/usr/bin/g++
      f77: /opt/rh/devtoolset-8/root/usr/bin/gfortran
      fc: /opt/rh/devtoolset-8/root/usr/bin/gfortran
    spec: gcc@8.3.1
    target: x86_64

