packages:
  all:
    compiler: [gcc]
    providers:
      mpi: [mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
    variants: build_type=Release
    target: [x86_64]
  cmake:
    externals:
    - spec: cmake@3.22.2
      prefix: /projects/wind/system-spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/cmake-3.22.2-s67tgoaqaw4ky5kmpuzxdg5une7xouvh/
    buildable: false
  mpich:
    externals:
    - spec: mpich@3.4.2%gcc@9.3.0
      prefix: /projects/wind/system-spack/opt/spack/linux-rhel7-x86_64/gcc-9.3.0/mpich-3.4.2-4h2muy6jlgfdahehxmxa4ybndfdb6gx2/
    - spec: mpich@3.4.2%gcc@8.3.1
      prefix: /projects/wind/spack-manager/views/system/gcc-8.3.1/mpich-3.4.2
