#!/bin/bash

. /projects/wind/spack-manager/spack/share/spack/setup-env.sh

env_name=$1

env_found=$(spack-python -c "from spack.main import SpackCommand;env=SpackCommand('env');print('${env_name}' in env('list'))")

if [ "$env_found" == "True" ]; then
  . $(spack location -e "${env_name}")/loads
else
 echo "Environment ${env_name} doesn't exist."
 echo "Available environments are:"
 echo $(spack-python -c "from spack.main import SpackCommand;env=SpackCommand('env');print(env('list'))")
fi