name: Spack-Manager Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{github.token}}
      - uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends graphviz
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx_rtd_theme myst-parser
      - name: Build
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          sphinx-build -M html ./docs ./build_docs/manual 2>&1 | tee -a build-output.txt
          mv ./build_docs/manual/html ./documentation
          touch ./documentation/.nojekyll
      - name: Report
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          egrep "WARNING:" build-output.txt | sort | uniq | \
            awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
          cat build-output-warnings.txt
          exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
      - name: Deploy
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: documentation
          SINGLE_COMMIT: true
