packages:
  all:
    permissions:
      read: group
      group: wg-sierra-users
    providers:
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
    variants: +mpi build_type=Release
  boost:
    version: [1.68.0]
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr/bin/pkg-config
  mpich:
    variants: netmod=ucx device=ch4 +slurm+hydra
  ucx:
    variants: +mlx5-dv+optimizations
  openmpi:
    variants: ~vt+pmi schedulers=slurm fabrics=auto legacylaunchers=true 
  slurm:
    externals:
    - spec: slurm@20.02.6
      prefix: /usr
    buildable: false
  openssl:
    version: [1.0.2]
    buildable: false
    externals:
    - spec: openssl@1.0.2
      prefix: /usr
  ncurses:
    version: [5.9]
    buildable: false
    externals:
    - spec: ncurses@5.9
      prefix: /usr
  ninja:
    externals::
    - spec: ninja@1.10.1
      modules:
      - cde/v2/ninja/1.10.1
  binutils:
    version: [2.29.1]
  zlib:
    version: [1.2.7]
    buildable: false
    externals:
    - spec: zlib@1.2.7
      prefix: /usr
  bzip2:
    version: [1.0.6]
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  m4:
    version: [1.4.16]
    buildable: false
    externals:
    - spec: m4@1.4.16
      prefix: /usr
